### ISSUE TITLE
Persistence disables other armor enchantments even when fully repaired.

### ISSUE THREAD

**Issue by Wiz3rd** [CJMinecraft01/NeverBreak#2]
Tested many times, easy to replicate, so it might be a bug in the code:
Whenever you apply Persistence to a piece of armor, it disables other enchantments completely.

Edit: they do not disable enchantments, but rather fall damage seems to not be reduced when Persistence is on.
Still an annoying bug though.

**Comment by CJMinecraft01** [comment]
Fixed in the latest version :)
