### ISSUE TITLE
[Request] Add enchantment description for compat with Quark and Enchantment Descriptions mods

### ISSUE THREAD

**Issue by jengendler** [CJMinecraft01/NeverBreak#4]
It's nice being able to see a short description of the enchantment with mods like Quark and Enchantment Descriptions, and it would be great to have this mod include support for that.

**Comment by CJMinecraft01** [comment]
Sorry for the extreme delay in responding to this. I've added this to the 1.16 version and intend to backport to the older Minecraft versions as soon as I can :)
